version: '3.8'

services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${EMAIL_GMAIL}
      - GF_SMTP_PASSWORD=${PASSWORD_APP_GMAIL}
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=grafana-alerts@email.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
    ports:
      - "3000:3000"
    volumes:
      - ./src/main/java/com/br/study/monitoring/grafana/provisioning/datasource/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/java/com/br/study/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml