scrape_configs:
  - job_name: monitoring-app
    metrics_path:  '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.0.187:8090']
        labels:
          application: 'monitoring-app'